### ISSUE TITLE
Figure out why release-plz can't keep single pr open

### ISSUE THREAD

**Issue by robert3005** [vortex-data/vortex#1067]

**Comment by danking** [comment]
I don't think this is happening any more?

**Comment by AdamGS** [comment]
I don't see any release-plz pr anymore

**Comment by danking** [comment]
Indeed, I’m spelunking into that now. Looks like when a release fails (0.21.0 was never released) release-plz gets a bit confused.

**Comment by danking** [comment]
Since the release failed, release-plz refuses to create a new PR because the version in git is larger than the version in crates. We fixed this by reverting the commit in main that incremented the version. This permitted release-plz to generate a PR.

Here's an example of the revert commit: https://github.com/spiraldb/vortex/commit/39936bff6069a951dd6e82c2843778664ab631ca
